title: 코딩코딩한 개발생활
author: 김완기
email: mycool0905@gamil.com
description: > # this means to ignore newlines until "show_exerpts:"
  코딩을 잘하고 싶은 청년의 블로그
show_excerpts: true # set to true to show excerpts on the homepage

# Google analytics
analytics:
  provider: "google"
  google:
    tracking_id: UA-178880198-1
    anonymize_ip: false # default

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  avatar: "/assets/images/portfolio.png"
  name: 김완기
  tagline: BE Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle

  # generate social links in footer
  social_links:
    github:  mycool0905
    instagram:  wan__gi
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
